//! Response handler script engine (spec 4.5).
//!
//! Runs an ES5.1 JavaScript snippet in a QuickJS sandbox (rquickjs) with a
//! minimal `client` / `response` / `assert` API surface (plan §5.5). Script
//! exceptions and `assert` failures are captured as [`Diagnostic`]s — they
//! never bubble to the caller, so subsequent requests still execute.
//!
//! Globals set via `client.global.set` persist across [`HandlerRuntime::run`]
//! calls on the same runtime, so an auth handler can stash a token that a
//! later request references via `{{token}}` (see Phase 3 / TDD P3-6).

use rquickjs::{
    context::Ctx, function::Rest, prelude::Coerced, CaughtError, Context, Function, IntoJs, Object,
    Runtime, Value,
};
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use std::time::{Duration, Instant};

use crate::dispatch::DispatchResponse;
use crate::error::{CoreError, Diagnostic, ErrorKind, Result, Span};

/// Default per-script timeout: 30 seconds. Guards against runaway scripts
/// (e.g. `while(true)`) hanging the dispatcher thread. The spec is silent
/// on handler timeouts; this is a project policy decision (plan §10 风险).
pub const DEFAULT_HANDLER_TIMEOUT: Duration = Duration::from_secs(30);

/// Per-run state shared between Rust and the JS sandbox via `Rc<RefCell>`.
/// A single `HandlerRuntime` can run multiple scripts; `globals` persist
/// across runs, while `logs` and `diagnostics` accumulate per-run.
#[derive(Default)]
struct HandlerState {
    globals: HashMap<String, String>,
    logs: Vec<String>,
    diagnostics: Vec<Diagnostic>,
}

/// Stateful ES5.1 response handler runtime (spec 4.5).
///
/// Cheap to construct; the heavy QuickJS `Runtime` is created lazily inside
/// [`HandlerRuntime::run`] so a no-op request (no `>` handler) pays nothing.
pub struct HandlerRuntime {
    state: Rc<RefCell<HandlerState>>,
    /// Per-script execution timeout. Override with [`Self::with_timeout`].
    timeout: Duration,
}

impl Default for HandlerRuntime {
    fn default() -> Self {
        Self::new()
    }
}

impl HandlerRuntime {
    /// Empty runtime with no globals, logs, or diagnostics, and the default
    /// per-script timeout ([`DEFAULT_HANDLER_TIMEOUT`]).
    pub fn new() -> Self {
        Self {
            state: Rc::new(RefCell::new(HandlerState::default())),
            timeout: DEFAULT_HANDLER_TIMEOUT,
        }
    }

    /// Set the per-script execution timeout. Applies to subsequent `run` /
    /// `run_file` calls. A timeout of `Duration::ZERO` disables the
    /// interrupt handler (scripts may run indefinitely).
    pub fn with_timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    /// Run `script` against `response`, mutating this runtime's state.
    /// JS exceptions are caught and recorded as a [`Diagnostic`] (kind
    /// `Handler`) — this method only returns `Err` for catastrophic
    /// QuickJS init failures, not for script errors. A script that exceeds
    /// the configured timeout is terminated via the QuickJS interrupt
    /// handler and recorded as a `Handler` diagnostic.
    pub fn run(&mut self, script: &str, response: &DispatchResponse) -> Result<()> {
        let runtime = Runtime::new().map_err(|e| handler_err("runtime init", e))?;
        let ctx = Context::full(&runtime).map_err(|e| handler_err("context init", e))?;

        // Install the interrupt handler BEFORE evaluating the script so
        // runaway loops (e.g. `while(true)`) are killed rather than hanging
        // the dispatcher. The handler returns `true` to raise an uncatchable
        // JS exception once `timeout` elapses since `start`.
        if self.timeout > Duration::ZERO {
            let start = Instant::now();
            let timeout = self.timeout;
            runtime.set_interrupt_handler(Some(Box::new(move || start.elapsed() >= timeout)));
        }

        let state = self.state.clone();
        ctx.with(|ctx| -> Result<()> {
            build_client_globals(&ctx, state.clone())?;
            build_assert(&ctx, state.clone())?;
            build_response(&ctx, response, state.clone())?;

            // Eval the script. Catch any JS exception as a Handler diagnostic
            // so the caller doesn't have to special-case script errors. Use
            // `CaughtError` to extract the actual exception value (e.g.
            // `Error: boom`) instead of the generic "Exception generated by
            // QuickJS" placeholder. Timeout-induced interrupts surface as
            // uncatchable exceptions and are caught here too.
            let eval_result: rquickjs::Result<Value> = ctx.eval(script);
            if let Err(e) = eval_result {
                let caught = CaughtError::from_error(&ctx, e);
                state.borrow_mut().diagnostics.push(Diagnostic {
                    kind: ErrorKind::Handler,
                    span: Span::new(0, 0),
                    message: format!("script error: {caught}"),
                });
            }
            Ok(())
        })
    }

    /// Load a script from `path` (spec 3.2.4 file-handler form `> file.js`)
    /// and run it. Missing file or read error returns `Err` of kind `Io`.
    pub fn run_file(&mut self, path: &str, response: &DispatchResponse) -> Result<()> {
        let script = std::fs::read_to_string(path).map_err(|e| {
            CoreError::new(
                ErrorKind::Io,
                Span::new(0, 0),
                format!("failed to read handler `{path}`: {e}"),
            )
        })?;
        self.run(&script, response)
    }

    /// Globals set via `client.global.set` during prior `run` calls.
    /// The caller can merge these into an [`crate::env::Environment`] so
    /// later requests can substitute `{{key}}` references (TDD P3-6).
    pub fn globals(&self) -> HashMap<String, String> {
        self.state.borrow().globals.clone()
    }

    /// `client.log(...)` output captured during the last (or latest
    /// accumulated) `run` calls.
    pub fn logs(&self) -> Vec<String> {
        self.state.borrow().logs.clone()
    }

    /// Diagnostics accumulated from `assert(false, msg)` failures and JS
    /// exceptions. The caller decides whether to surface these to the UI or
    /// fail the batch — they never abort execution within the sandbox.
    pub fn diagnostics(&self) -> Vec<Diagnostic> {
        self.state.borrow().diagnostics.clone()
    }
}

fn handler_err(prefix: &str, e: rquickjs::Error) -> CoreError {
    CoreError::new(
        ErrorKind::Handler,
        Span::new(0, 0),
        format!("{prefix}: {e}"),
    )
}

/// Install `client.global`, `client.log` on the global object.
fn build_client_globals(ctx: &Ctx, state: Rc<RefCell<HandlerState>>) -> Result<()> {
    let client = Object::new(ctx.clone()).map_err(|e| handler_err("client obj", e))?;
    let global_obj = Object::new(ctx.clone()).map_err(|e| handler_err("global obj", e))?;

    // client.global.set(key, value) — coerce value to string for storage.
    // spec 4.5: globals persist across requests so handlers can hand values
    // to later requests. Coercion mirrors `String(value)` (numbers → digits,
    // strings → verbatim, objects → "[object Object]"; use JSON.stringify
    // explicitly to serialize objects).
    let st_for_set = state.clone();
    let set_fn = Function::new(ctx.clone(), move |key: String, value: Coerced<String>| {
        st_for_set.borrow_mut().globals.insert(key, value.0);
    })
    .map_err(|e| handler_err("client.global.set", e))?;
    global_obj
        .set("set", set_fn)
        .map_err(|e| handler_err("client.global.set install", e))?;

    // client.global.get(key) -> string | undefined
    let st_for_get = state.clone();
    let get_fn = Function::new(ctx.clone(), move |key: String| -> Option<String> {
        st_for_get.borrow().globals.get(&key).cloned()
    })
    .map_err(|e| handler_err("client.global.get", e))?;
    global_obj
        .set("get", get_fn)
        .map_err(|e| handler_err("client.global.get install", e))?;

    client
        .set("global", global_obj)
        .map_err(|e| handler_err("client.global install", e))?;

    // client.log(...args) — coerce each arg, join with single space.
    let st_for_log = state.clone();
    let log_fn = Function::new(ctx.clone(), move |args: Rest<Coerced<String>>| {
        let joined = args
            .0
            .iter()
            .map(|c| c.0.as_str())
            .collect::<Vec<_>>()
            .join(" ");
        st_for_log.borrow_mut().logs.push(joined);
    })
    .map_err(|e| handler_err("client.log", e))?;
    client
        .set("log", log_fn)
        .map_err(|e| handler_err("client.log install", e))?;

    ctx.globals()
        .set("client", client)
        .map_err(|e| handler_err("client install", e))?;
    Ok(())
}

/// Install the global `assert(cond, msg)` function (spec 4.5 — `assert`
/// is a top-level, not `client.assert`). On failure, records a diagnostic
/// and continues execution (does NOT throw).
fn build_assert(ctx: &Ctx, state: Rc<RefCell<HandlerState>>) -> Result<()> {
    let st = state.clone();
    let assert_fn = Function::new(ctx.clone(), move |cond: bool, msg: String| {
        if !cond {
            st.borrow_mut().diagnostics.push(Diagnostic {
                kind: ErrorKind::Handler,
                span: Span::new(0, 0),
                message: msg,
            });
        }
    })
    .map_err(|e| handler_err("assert", e))?;
    ctx.globals()
        .set("assert", assert_fn)
        .map_err(|e| handler_err("assert install", e))?;
    Ok(())
}

/// Install the `response` object: `status` (number), `body` (string or
/// parsed JSON object), `headers.value(name)` (case-insensitive).
fn build_response(
    ctx: &Ctx,
    response: &DispatchResponse,
    state: Rc<RefCell<HandlerState>>,
) -> Result<()> {
    let resp_obj = Object::new(ctx.clone()).map_err(|e| handler_err("response obj", e))?;

    // status: number
    resp_obj
        .set("status", response.status)
        .map_err(|e| handler_err("response.status", e))?;

    // body: if Content-Type indicates JSON, parse via JS JSON.parse so the
    // script can navigate the object (`response.body.token`). Otherwise body
    // is a plain string. Non-UTF-8 bodies are replaced with a replacement
    // string; spec 4.5 is silent on binary, but a JS handler can't make sense
    // of binary anyway.
    let content_type = response.header("Content-Type").unwrap_or("");
    let body_value: Value = if content_type
        .to_ascii_lowercase()
        .contains("application/json")
    {
        let body_str = String::from_utf8_lossy(&response.body).into_owned();
        let json_obj: Object = ctx
            .globals()
            .get("JSON")
            .map_err(|e| handler_err("JSON lookup", e))?;
        let parse_fn: Function = json_obj
            .get("parse")
            .map_err(|e| handler_err("JSON.parse lookup", e))?;
        let body_js_str = body_str
            .into_js(ctx)
            .map_err(|e| handler_err("body into_js", e))?;
        let parsed: Value = parse_fn
            .call((body_js_str,))
            .map_err(|e| {
                // Surface a parse error as a diagnostic instead of bubbling.
                state.borrow_mut().diagnostics.push(Diagnostic {
                    kind: ErrorKind::Handler,
                    span: Span::new(0, 0),
                    message: format!("JSON.parse failed: {e}"),
                });
                e
            })
            .unwrap_or_else(|_| Value::new_undefined(ctx.clone()));
        parsed
    } else {
        let body_str = String::from_utf8_lossy(&response.body).into_owned();
        body_str
            .into_js(ctx)
            .map_err(|e| handler_err("body string", e))?
    };
    resp_obj
        .set("body", body_value)
        .map_err(|e| handler_err("response.body install", e))?;

    // headers object with value(name) — case-insensitive lookup.
    let headers_obj = Object::new(ctx.clone()).map_err(|e| handler_err("headers obj", e))?;
    let headers_snapshot: Vec<(String, String)> = response.headers.clone();
    let value_fn = Function::new(ctx.clone(), move |name: String| -> Option<String> {
        headers_snapshot
            .iter()
            .find(|(n, _)| n.eq_ignore_ascii_case(&name))
            .map(|(_, v)| v.clone())
    })
    .map_err(|e| handler_err("headers.value", e))?;
    headers_obj
        .set("value", value_fn)
        .map_err(|e| handler_err("headers.value install", e))?;
    resp_obj
        .set("headers", headers_obj)
        .map_err(|e| handler_err("response.headers install", e))?;

    ctx.globals()
        .set("response", resp_obj)
        .map_err(|e| handler_err("response install", e))?;
    Ok(())
}
